services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm install -g json-server@0.17.4 && json-server --watch /app/db.json --host 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"
